package com.chepra.mvptodo.Database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chepra.mvptodo.Database.TaskModel;

import com.chepra.mvptodo.Database.TaskModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskModelDaoConfig;

    private final TaskModelDao taskModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskModelDaoConfig = daoConfigMap.get(TaskModelDao.class).clone();
        taskModelDaoConfig.initIdentityScope(type);

        taskModelDao = new TaskModelDao(taskModelDaoConfig, this);

        registerDao(TaskModel.class, taskModelDao);
    }
    
    public void clear() {
        taskModelDaoConfig.clearIdentityScope();
    }

    public TaskModelDao getTaskModelDao() {
        return taskModelDao;
    }

}
